apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
        - image: clickhouse/clickhouse-server:latest
          name: clickhouse
          ports:
            - containerPort: 8123
              protocol: TCP
            - containerPort: 9000
              protocol: TCP
            - containerPort: 9009
              protocol: TCP
          imagePullPolicy: Never