apiVersion: v1
kind: Service
metadata:
  name: clickhouse
spec:
  selector:
    app: clickhouse
  ports:
    # - protocol: TCP
    #   name: "8123"
    #   port: 8123
    #   targetPort: 8123
    - protocol: TCP
      name: "9000"
      port: 9000
      targetPort: 9000
    # - protocol: TCP
    #   name: "9009"
    #   port: 9009
    #   targetPort: 9009
